config/routes.rb
Rails.application.routes.draw do

  #devise_for :users


#devise_for :users,
  #:skip => [:registrations, :sessions]

#as user do
  # Registrations
  #get   '/signup'   => 'users/registrations#new', as: :new_user_registration
  #post  '/signup'   => 'users/registrations#create', as: :user_registration
#end




  resources :receipt_lines
  resources :receipts
  resources :paymentlines
  resources :payments
  resources :items
  resources :cashes
  resources :banks
  resources :accharts
  resources :invoice_lines
  resources :invoices
  resources :customers
# You can have the root of your site routed with "root"
  root to: 'dashboards#dashboard_1'

  # All routes
  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"
  get "dashboards/dashboard_5"

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/chartist"
  get "graphs/peity"
  get "graphs/sparkline"
  get "graphs/c3charts"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "metrics/index"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"
  get "forms/autocomplete"
  get "forms/markdown"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/profile_two"
  get "appviews/contacts_two"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/activity_stream"
  get "appviews/file_menager"
  get "appviews/vote_list"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/social_feed"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/datamaps"
  get "miscellaneous/social_buttons"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/pdf_viewer"
  get "miscellaneous/sweet_alert"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/spinners_usage"
  get "miscellaneous/live_favicon"
  get "miscellaneous/masonry"
  get "miscellaneous/tour"
  get "miscellaneous/loading_buttons"
  get "miscellaneous/clipboard"
  get "miscellaneous/text_spinners"
  get "miscellaneous/truncate"
  get "miscellaneous/password_meter"
  get "miscellaneous/i18support"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/resizeable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/tabs"
  get "uielements/notifications_tooltips"
  get "uielements/helper_classes"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/foo_tables"
  get "tables/jqgrid"

  get "commerce/products_grid"
  get "commerce/products_list"
  get "commerce/product_edit"
  get "commerce/product_detail"
  get "commerce/orders"
  get "commerce/cart"
  get "commerce/payments"

  get "gallery/basic_gallery"
  get "gallery/slick_carusela"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

  get "landing/index"


# routes for adding fields dynamically
  get '/add_field', to: 'invoices#add_field', as: 'add_field'
  post '/add_field', to: 'invoices#add_field'

end

app/models/acchart.rb
class Acchart < ApplicationRecord
end

app/models/bank.rb
class Bank < ApplicationRecord
end

app/models/cash.rb
class Cash < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
 
   
has_many :invoice_lines, dependent: :destroy

#accepts_nested_attributes_for :invoice_lines

  accepts_nested_attributes_for :invoice_lines

    #accepts_nested_attributes_for :invoice_lines
     #def invoice_lines_attributes=(hash)
	  #  if !!self.id
	     # self.invoice_lines.clear
	     # hash.values.each do |attributes|
		#attrs = attributes.merge({invoice_id: self.id})
		#self.invoice_lines << InvoiceLine.find_or_create_by(attrs)
	    #  end
	  # end
	 # end

end

app/models/invoice1.rb
class Invoice < ApplicationRecord
end

app/models/invoice_line.rb
class InvoiceLine < ApplicationRecord
  belongs_to :invoice, primary_key: 'id'


end

app/models/invoice_line1.rb
class InvoiceLine < ApplicationRecord
  belongs_to :invoice
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
has_many :paymentlines, dependent: :destroy

#accepts_nested_attributes_for :invoice_lines

  accepts_nested_attributes_for :paymentlines

end

app/models/paymentline.rb
class Paymentline < ApplicationRecord
  belongs_to :payment
end

app/models/receipt.rb
class Receipt < ApplicationRecord
has_many :receipt_lines, dependent: :destroy

#accepts_nested_attributes_for :invoice_lines

  accepts_nested_attributes_for :receipt_lines
end

app/models/receipt_line.rb
class ReceiptLine < ApplicationRecord
  belongs_to :receipt
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/accharts_helper.rb
module AcchartsHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/cashes_helper.rb
module CashesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/invoices4/_form.html.erb
<%= form_with(model: invoice, local: true) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_name %>
    <%= form.text_area :customer_name %>
  </div>

  <div class="field">
    <%= form.label :contactno %>
    <%= form.text_area :contactno %>
  </div>

  <div class="field">
    <%= form.label :contact_name %>
    <%= form.text_area :contact_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_area :city %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :sales_person_code %>
    <%= form.text_area :sales_person_code %>
  </div>

  <div class="field">
    <%= form.label :sales_person_name %>
    <%= form.text_area :sales_person_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices4/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices4/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Customer name</th>
      <th>Contactno</th>
      <th>Contact name</th>
      <th>Address</th>
      <th>City</th>
      <th>Date</th>
      <th>Sales person code</th>
      <th>Sales person name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.customer_name %></td>
        <td><%= invoice.contactno %></td>
        <td><%= invoice.contact_name %></td>
        <td><%= invoice.address %></td>
        <td><%= invoice.city %></td>
        <td><%= invoice.date %></td>
        <td><%= invoice.sales_person_code %></td>
        <td><%= invoice.sales_person_name %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices4/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices4/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer name:</strong>
  <%= @invoice.customer_name %>
</p>

<p>
  <strong>Contactno:</strong>
  <%= @invoice.contactno %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @invoice.contact_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @invoice.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @invoice.city %>
</p>

<p>
  <strong>Date:</strong>
  <%= @invoice.date %>
</p>

<p>
  <strong>Sales person code:</strong>
  <%= @invoice.sales_person_code %>
</p>

<p>
  <strong>Sales person name:</strong>
  <%= @invoice.sales_person_name %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

app/views/layouts/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <%= link_to root_path, class: "navbar-brand" do %>
        <i class="far fa-file-pdf"></i>
        <span class="m-l-2">Rails Generate PDFs</span>
      <% end %>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

      </ul>

      <% if action_name.to_sym == :show %>
        <%= link_to 'Back', root_path, class: "btn btn-outline-secondary mx-2" %>
        <%= link_to 'DOWNLOAD PDF', invoice_path(::Invoice.find(params[:id]), format: :pdf), class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>

    </div>
  </div>
</nav>