config/routes.rb
Rails.application.routes.draw do

  #devise_for :users


#devise_for :users,
  #:skip => [:registrations, :sessions]

#as user do
  # Registrations
  #get   '/signup'   => 'users/registrations#new', as: :new_user_registration
  #post  '/signup'   => 'users/registrations#create', as: :user_registration
#end




  resources :receipt_lines
  resources :receipts
  resources :paymentlines
  resources :payments
  resources :items
  resources :cashes
  resources :banks
  resources :accharts
  resources :invoice_lines
  resources :invoices
  resources :customers
# You can have the root of your site routed with "root"
  root to: 'dashboards#dashboard_1'

  # All routes
  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"
  get "dashboards/dashboard_5"

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/chartist"
  get "graphs/peity"
  get "graphs/sparkline"
  get "graphs/c3charts"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "metrics/index"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"
  get "forms/autocomplete"
  get "forms/markdown"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/profile_two"
  get "appviews/contacts_two"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/activity_stream"
  get "appviews/file_menager"
  get "appviews/vote_list"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/social_feed"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/datamaps"
  get "miscellaneous/social_buttons"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/pdf_viewer"
  get "miscellaneous/sweet_alert"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/spinners_usage"
  get "miscellaneous/live_favicon"
  get "miscellaneous/masonry"
  get "miscellaneous/tour"
  get "miscellaneous/loading_buttons"
  get "miscellaneous/clipboard"
  get "miscellaneous/text_spinners"
  get "miscellaneous/truncate"
  get "miscellaneous/password_meter"
  get "miscellaneous/i18support"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/resizeable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/tabs"
  get "uielements/notifications_tooltips"
  get "uielements/helper_classes"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/foo_tables"
  get "tables/jqgrid"

  get "commerce/products_grid"
  get "commerce/products_list"
  get "commerce/product_edit"
  get "commerce/product_detail"
  get "commerce/orders"
  get "commerce/cart"
  get "commerce/payments"

  get "gallery/basic_gallery"
  get "gallery/slick_carusela"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

  get "landing/index"


# routes for adding fields dynamically
  get '/add_field', to: 'invoices#add_field', as: 'add_field'
  post '/add_field', to: 'invoices#add_field'

end

app/models/invoice.rb
class Invoice < ApplicationRecord
 
   
has_many :invoice_lines, dependent: :destroy

#accepts_nested_attributes_for :invoice_lines

  accepts_nested_attributes_for :invoice_lines

    #accepts_nested_attributes_for :invoice_lines
     #def invoice_lines_attributes=(hash)
	  #  if !!self.id
	     # self.invoice_lines.clear
	     # hash.values.each do |attributes|
		#attrs = attributes.merge({invoice_id: self.id})
		#self.invoice_lines << InvoiceLine.find_or_create_by(attrs)
	    #  end
	  # end
	 # end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

before_action :set_invoice, only: %i[ show edit update destroy ]
  before_action :find_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices or /invoices.json
  def index
    @invoices = Invoice.all
     @invoices = scope
  end







  # GET /invoices/1 or /invoices/1.json
  

  def show
    @invoice = scope.find(params[:id])

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Invoice No. #{@invoice.id}",
        page_size: 'A4',
        template: "invoices/show.html.erb",
        layout: "pdf.html",
        orientation: "Landscape",
        lowquality: true,
        zoom: 1,
        dpi: 75
      end
    end
 


  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @invoice.invoice_lines.build
  end







  # GET /invoices/1/edit 
  def edit
  end

  # POST /invoices or /invoices.json
 #  def create
  #  @invoice = Invoice.new(invoice_params)

   #  respond_to do |format|
    #   if @invoice.save
      #  format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully created." }
       #  format.json { render :show, status: :created, location: @invoice }
     #  else
      #  format.html { render :new, status: :unprocessable_entity }
       #  format.json { render json: @invoice.errors, status: :unprocessable_entity }
      # end
     #end
 # end




# def create
  #   @invoice = invoices.build(invoice_params)
   #  invoice_params[:invoice_lines_attributes].each do |num,product|
    #   @invoice.invoice_lines.build(product)
   
# end 
   
       ##flash[:alert] = @invoice.errors.full_messages.uniq
      # #render :new


  #  if @invoice.valid?
    #   @invoice.save
     
     #  flash[:notice] = "Invoice created successfully!"
      # redirect_to invoice_path(@invoice, @invoice)
   #  else
     #  flash[:alert] = @invoice.errors.full_messages.uniq
     #  render :new
    # end
    
 # end


 






  # PATCH/PUT /invoices/1 or /invoices/1.json
  # def update
    # respond_to do |format|
       #if @invoice.update(invoice_params)
       #  format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully updated." }
        # format.json { render :show, status: :ok, location: @invoice }
       #else
        # format.html { render :edit, status: :unprocessable_entity }
        # format.json { render json: @invoice.errors, status: :unprocessable_entity }
      # end
     #end
  # end


 def update
   if @invoice.update(invoice_params)
     flash[:notice] = "Updated invoice successfully!"
     # @invoice.calculate_product_totals
      redirect_to invoice_path(@invoice)
    else
     flash[:alert] = @invoice.errors.full_messages.uniq
      render :edit
    end
  end






  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_field
    respond_to do |format|
      format.js {render layout: false}
    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
  def invoice_params
   params.require(:invoice).permit(:customer_no, :custoner_name, :contactno, :contact_name, :address, :city, :date, :sale_person_code, :sale_person_name,     invoice_lines_attributes: [:charge_type, :item_no, :description, :quantity, :unit_of_measure, :unit_price, :amount, :_destroy])
  end

def scope
      ::Invoice.all.includes(:invoice_lines)
    end

def find_invoice
   @invoice = Invoice.find_by(id: params[:id])
  end

end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/old2/_field.html.erb
<!-- This partial is currently not being used -->
<!-- If you see this in the page source then somethings not right -->
<tr id="row-0 input-group">
  <th scope="row" id="product-num"></th>

  <div class="field">
  </div>
  <td><%= ff.collection_select :product_id, Product.all, :id, :name, include_blank: 'Select a product' %></td>
  <!-- <td><%#<%= ff.select :product_id, options_from_collection_for_select(Product.all, :id, :name), include_blank: 'Select a product' %></td> -->


  <div class="field">
  </div>
  <td><%= ff.text_field :quantity, size: '1em', class: 'form-control text-center', onchange: 'showTotal(this)' %></td>

  <div class="field">
  </div>
  <td><%= ff.text_field :total, size: '2em', class: 'form-control text-center', readonly: true %></td>

  <div class="field">
  </div>
  <td><%= link_to "Delete", "", class: 'btn btn-danger float-right remove-field' %></td>
</tr>

app/views/invoices/old2/_invoice_form.html.erb
<%= form_for invoice do |f| %>

  <div class="row">

    <div class="col">
      <h4>Users Business Name</h4>
      <address class="">
        1 Address Here City, State 00000 (user address)
      </address>
    </div>

    <div class="col">
      <span class="inline-headers">
        <h2>Invoice ID: <%= invoice.id || Invoice.all.count+1 %>  </h2>
      </span>

    </div>
  </div>

  <div class="row">
    <div class="col">
      <h4>Bill To Account</h4>

      <% if !!params[:account_id] %>
        <%= f.collection_select(:account_id, current_user.accounts, :id, :name, {}, {class: 'form-control custom-input'}) %>
      <% else %>
        <div class="field">
          <%= f.select(:account_id, current_user.accounts.collect {|a| [a.name, a.id]}, prompt: "Select Account", class: 'form-control custom-input') %>
        </div>
      <% end %>

      <br>
      <%= link_to "Create New Account", new_account_path %>
    </div>

    <div class="col">
      <div class="field">
        <h5>Date Created: <%= f.date_field  :created_at, value: Time.now.strftime('%Y-%m-%d'), class: 'form-control date-select'  %></h5>
      </div>
      <br>
        <div class="field">
          <h5>Date Due: <%= f.date_field :due_time, value: (Time.now+7*86400).strftime('%Y-%m-%d'), class: 'form-control date-select' %> </h5>
        </div>
    </div>
  </div>

  <div class="row border border-dark bg-dark">
    <div class="col">
      <table class="table table-dark">
        <thead class="text-center">
          <tr>
            <th scope="col">#</th>
            <th scope="col" class='text-left'>Product</th>
            <th scope="col">Quantity</th>
            <th scope="col"></th>
          </tr>
        </thead>

        <tbody id="table-body" class="fields" >

          <% @invoice.invoice_products.each do |product| %>
            <%= f.fields_for :invoice_products,product do |ff| %>
              <%= render partial: 'invoice_product_field', locals: {ff: ff} %>
            <% end %>
          <% end %>
        </tbody>

      </table>

    </div>
  </div>

  <div class="row border border-dark p-2">
    <%= link_to "Add Product", add_field_path(format: :js), {method: :post, remote: true, id: "addProductBtn", class: 'btn btn-primary'} %>

    <div class="col">

    </div>

    <div class="col">
      <div class="row">
        <div class="col">
          Sub Total:
        </div>
        <div class="col">
          <!--  we need to fix the precision on the totals at some point -->
          $ <%= @invoice.amount_due %>
        </div>
      </div>

      <div class="row font-weight-bold">
        <div class="col">
          Grand Total Due:
        </div>
        <div class="col">
          <!--  we need to fix the precision on the totals at some point -->
          $ <%= @invoice.grand_total unless request.url.match('/invoices/new')%>
        </div>
      </div>
    </div>
  </div>


  <div class="row action">
    <div class="col-10">
    </div>

    <div class="float-right col-2">
      <%= f.submit class: 'btn btn-primary mt-3' %>
    </div>

  </div>

<script type="text/javascript">

  function showTotal(e){
    alert('workin');
  }

  function deleteRow(row){
    row.parentNode.deleteRow(row.rowIndex-1);
    return true;
  }

  document.addEventListener('click', (e) => {
    if (e.target.id == 'delete-row'){
      e.target.parentElement.parentElement.parentElement.removeChild(e.target.parentElement.parentElement)
      numberProducts()
    }
  })

  var deleteBtns = document.getElementsByClassName("remove-field");

  for (var i=0; i<deleteBtns.length; i++){
    deleteBtns[i].addEventListener('click', function(e){
      e.target.parentElement.parentElement.parentElement.removeChild(e.target.parentElement.parentElement)
    });
  }

  document.addEventListener("DOMContentLoaded", function(){

    let tBody = document.getElementById("table-body");
    let addBtn = document.getElementById("addProductBtn");

    function nameFields(){
      let selects = tBody.getElementsByTagName('select');
      for (var i=0;i < selects.length; i++){
        // selects[i].name = "invoice[invoice_products_attributes][" +i+ "][product_id]";
        selects[i].name = `invoice[invoice_products_attributes][${i}][product_id]`;
        selects[i].id = `invoice[invoice_products_attributes][${i}][product_id]`;
        selects[i].parentElement.previousSibling.previousSibling.innerHTML = (i+1);
        // selects[i].parentNode.nextSibling.nextElementSibling.firstElementChild.name = "invoice[invoice_products_attributes]["+i+"][quantity]";
        selects[i].parentNode.nextSibling.nextElementSibling.firstElementChild.name = `invoice[invoice_products_attributes][${i}][quantity]`;
        // selects[i].parentNode.nextSibling.nextElementSibling.firstElementChild.id = "invoice[invoice_products_attributes]["+i+"][quantity]";
        selects[i].parentNode.nextSibling.nextElementSibling.firstElementChild.id = `invoice[invoice_products_attributes][${i}][quantity]`;
      }
    }


    addBtn.addEventListener('click', function(){
      setTimeout(nameFields, 300);
    })

    numberProducts();
  });

  function numberProducts(){
    debugger
    let tBody = document.getElementById("table-body");
    let selects = tBody.getElementsByTagName('tr');
    for (var i=0;i < selects.length; i++){
      selects[i].firstElementChild.innerText = i+1;
    }
  }


</script>
<% end %>

app/views/invoices/old2/_invoice_listing.html.erb
<tr>
  <td colspan="1"><%= invoice.id %></td>
  <td colspan="4"><%= invoice.custoner_name %></td>
  <td colspan="3"><%= invoice.contactno %></td>
  <td colspan="3"><%= invoice.contact_name %></td>
  <td colspan="3"><%= link_to "Edit", edit_invoice_path(invoice), class: 'btn btn-info' %></td>
  <td> <%= button_to "Delete", invoice_path(invoice), method: :delete, class: 'btn btn-danger' %></td>
  <td><%= link_to "View", invoice_path(invoice), class: 'btn btn-primary' %></td>
    
 
</tr>

app/views/invoices/old2/_list_invoices.html.erb
<table class="container">
  <tbody class="table table-hover">
    <tr>
      <th colspan="1">ID</th>
      <th colspan="4">Client</th>
      <th colspan="3">Status</th>
      <th colspan="3">Amount Due</th>
      <th colspan="3">Due Date</th>
      <th class="text-center" colspan="6">Controls</th>
    </tr>

    <% if invoices && invoices.count > 1 %>

      <% invoices.each do |invoice| %>

        <%= render partial: 'invoice_listing', locals: {invoice: invoice} %>

      <% end %>

    <% elsif invoices.count == 1 %>

      <%= render partial: 'invoice_listing', locals: {invoice: invoices.first} %>

    <% else %>
      <h2>No Clients to Display!</h2>
    <% end %>

  </tbody>
</table>

app/views/invoices/old2/_show_invoice.html.erb
<div class="row mb-5">

  <div class="col">
    <%= link_to "Send", send_invoice_url(id: @invoice, only_path: true), class: 'btn btn-primary' %>
    <%= link_to "Edit", edit_invoice_path(@invoice), class: 'btn btn-warning' %>
    <%= link_to "Delete", invoice_path(@invoice), method: :delete, class: 'btn btn-danger float-right' %>
  </div>

</div>

<div class="row">
  <div class="col">
    <h3 class="bg-info pr-5 pl-5 text-white">Invoice for <%= @invoice.account.client.business_name %></h3>
  </div>


  <div class="col">
    <%= image_tag "logo.png", class: 'float-right' %>
  </div>
</div>


<div class="row p-2 border-right border-left border-top border-dark">

  <div class="col">
    <h4>Users Business Name</h4>
    <address class="">
      1 Address Here City, State 00000 (user address)
    </address>
  </div>

  <div class="col">
    <h2>Invoice #: <%= @invoice.id %></h2>
  </div>
</div>

<div class="row border-left border-right border-dark">

  <div class="col m-4">
    <h4>Bill To</h4>
    <p>
      <%= @invoice.account.client.name %>
      <br>
      <%= @invoice.account.client.business_name %>
      <address class="">
        <%= @invoice.account.client.address %>
      </address>
      <%= @invoice.account.client.phone_number %>
      <br>
      <a href="<%= @invoice.account.client.email %>"><%= @invoice.account.client.email %></a>
    </p>
  </div>

  <div class="col">
    <h5>Date Created: <%= @invoice.created_at.strftime("%Y-%m-%d") %></h5>
    <br>
    <h5>Date Due:  <%= @invoice.due_time.strftime("%Y-%m-%d") %></h5>
  </div>
</div>

<div class="row border border-dark bg-dark">
  <div class="col">
    <table class="table table-dark">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Product</th>
          <th scope="col" colspan="2">Description</th>
          <th scope="col">Quantity</th>
          <th scope="col">Rate</th>
          <th scope="col">Total</th>
        </tr>
      </thead>
      <tbody>
        <% @invoice.invoice_products.each do |invoice_product| %>
          <tr>
            <th scope="row" colspan="1"><%= invoice_product.product.id %></th>
            <td><%= invoice_product.product.name %></td>
            <td colspan="2"><%= invoice_product.product.description %></td>
            <td><%= invoice_product.quantity %></td>
            <td>$<%= invoice_product.product.price %></td>
            <td>$<%= invoice_product.total %><td>
          </tr>

        <% end %>

      </tbody>
    </table>


  </div>
</div>

<br>

<div class="row bg-info text-white pt-2 pb-">

  <div class="col-7">

  </div>

  <div class="col-5">
    <div class="row">
      <div class="col">
        Sub Total:
      </div>
      <div class="col">
        <!--  we need to fix the precision on the totals at some point -->
        $<%= invoice.grand_total.to_f.round(2) %>
      </div>
    </div>

    <div class="row font-weight-bold">
      <div class="col">
        Grand Total Due:
      </div>
      <div class="col">
        <!--  we need to fix the precision on the totals at some point -->
        $<%= invoice.grand_total.to_f.round(2) %>
      </div>
    </div>
  </div>
</div>

app/views/invoices/old2/add_field.js.erb
$("#table-body").append(`
  <tr id="input-group">
    <th scope="row" id="product-num"></th>
    <td><%= select_tag :product_id, options_from_collection_for_select(Product.all, :id, :name), include_blank: 'Select a product'%></td>
    <td><input size="1em" class="form-control text-center" type="text" value="1" name="invoice[invoice_products_attributes][0][quantity]" id="invoice_invoice_products_attributes_0_quantity"></td>
    <td><a class="btn btn-danger float-right remove-field" id="delete-row">Delete</a></td>
  </tr>
`)

app/views/invoices/old2/edit.html.erb
<h1 class="text-center">Edit Invoice</h1>

<div class="invoice mt-5">

  <%= form_for @invoice, url: {controller: 'invoices', action: 'update', id: @invoice  } do |f| %>
    <% hidden_field_tag(:invoice, :id) %>
    <div class="row">

      <div class="col">
        <h4>Users Business Name</h4>
        <address class="">
          1 Address Here City, State 00000 (user address)
        </address>
      </div>

      <div class="col">
        <span class="inline-headers">
          <h2>Invoice ID: <%= @invoice.id || Invoice.all.count+1 %>  </h2>
        </span>

      </div>
    </div>

    <div class="row">
      <div class="col">
        <h4>Bill To Account</h4>

        <br>
      
      </div>

      <div class="col">
        <div class="field">
          <h5>Date Created: <%= f.date_field  :created_at, value: Time.now.strftime('%Y-%m-%d'), class: 'form-control date-select'  %></h5>
        </div>
        <br>
          <div class="field">
            <h5>Date Due: <%= f.date_field :due_time, value: (Time.now+7*86400).strftime('%Y-%m-%d'), class: 'form-control date-select' %> </h5>
          </div>
      </div>
    </div>

    <div class="row border border-dark bg-dark">
      <div class="col">
        <table class="table table-dark">
          <thead class="text-center">
            <tr>
              <th scope="col">#</th>
              <th scope="col" >Product</th>
              <th scope="col">Quantity</th>
              <th scope="col" >Total</th>
              <th scope="col"></th>
            </tr>
          </thead>

          <tbody id="table-body" class="fields" >

            <%# <% @invoice.invoice_products1.each do |product| %>
              <%= f.fields_for :invoice_products do |ff| %>
                <%= render partial: 'field', locals: {ff: ff} %>
              <% end %>
            <%# <% end  %>
          </tbody>

        </table>

      </div>
    </div>

    <div class="row border border-dark p-2">
      <%= link_to "Add Product", add_field_path(format: :js), {method: :post, remote: true, id: "addProductBtn", class: 'btn btn-primary'} %>

      <div class="col">

      </div>

      <div class="col">
        <div class="row">
          <div class="col">
            Sub Total:
          </div>
          <div class="col">
            <!--  we need to fix the precision on the totals at some point -->
            $ <%= @invoice.amount_due %>
          </div>
        </div>

        <div class="row font-weight-bold">
          <div class="col">
            Grand Total Due:
          </div>
          <div class="col">
            <!--  we need to fix the precision on the totals at some point -->
            $ <%= @invoice.grand_total unless request.url.match('/invoices/new')%>
          </div>
        </div>
      </div>
    </div>


    <div class="row action">
      <div class="col-10">
      </div>

      <div class="float-right col-2">
        <%= f.submit "Update Invoice", class: 'btn btn-primary' %>
      </div>

    </div>


  <% end %>


  <script type="text/javascript">


    function deleteRow(row){
      row.parentNode.deleteRow(row.rowIndex-1);
      return true;
    }

    var deleteBtns = document.getElementsByClassName("remove-field");

    for (var i=0; i<deleteBtns.length; i++){
      deleteBtns[i].addEventListener('click', function(e){
        e.preventDefault()
        var elem = e.target;
        var row = elem.parentNode.parentNode;
        deleteRow(row);
      });
    }
    $(".remove-field").on('click', function(e){
      e.preventDefault()
      var elem = e.target;
      var row = elem.parentNode.parentNode;
      deleteRow(row);
    });

    document.addEventListener("DOMContentLoaded", function(){

      let tBody = document.getElementById("table-body");
      let addBtn = document.getElementById("addProductBtn");

      function nameFields(){
        let selects = tBody.getElementsByTagName('select');
        for (var i=0;i < selects.length; i++){
          selects[i].name = `invoice[invoice_products_attributes][${i}][product_id]`;
          selects[i].id = `invoice[invoice_products_attributes][${i}][product_id]`;
          selects[i].parentElement.previousSibling.previousSibling.innerHTML = (i+1);
          selects[i].parentNode.nextSibling.nextElementSibling.firstElementChild.name = `invoice[invoice_products_attributes][${i}][quantity]`;
          selects[i].parentNode.nextSibling.nextElementSibling.firstElementChild.id = `invoice[invoice_products_attributes][${i}][quantity]`;
        }
      }

      function numberProducts(){
        let selects = tBody.getElementsByTagName('select');
        for (var i=0;i < selects.length; i++){
          selects[i].parentElement.previousSibling.previousSibling.append(i+1);
        }
      }

      addBtn.addEventListener('click', function(){
        setTimeout(nameFields, 300);
      })

      numberProducts();
    });


  </script>


</div>

app/views/invoices/old2/index.html.erb
<h1 class="text-center">My Invoices</h1>


<div class="card">
  <div class="card-header d-flex flex-row bd-highlight p-4">

    <div class="pr-2">
      <% if params[:account_id] %>
        <%= button_to "Create Invoice",new_account_invoice_path, method: 'get',class: 'btn btn-primary' %>
      <% else %>
        <%= button_to "Create Invoice",new_invoice_path, method: 'get',class: 'btn btn-primary' %>
      <% end %>
    </div>

    <div class="container-fluid mr-0">
      
    </div>
  </div>

  <div class="container-fluid">
    <%= render partial: 'list_invoices', locals: {invoices: @invoices} %>
  </div>

</div>

app/views/invoices/old2/new.html.erb
<h1 class="text-center">Create new Invoice</h1>

<% if Client.all.count < 1 %>

  <div class="alert alert-danger">
    You have no clients to select yet! <br>
    Please <%= link_to "create a client", new_client_path %> before creating a invoice!
  </div>

<% elsif current_user.accounts.count < 1 %>
  <div class="alert alert-danger">
    You have no accounts to choose from! <br>
    Please <%= link_to "create a account", new_account_path %> with a client before creating a invoice!
  </div>

<% elsif Product.all.count < 1 %>

  <div class="alert alert-danger">
    You have no products to add to a invoice yet!
    Please <%= link_to "create a product", new_product_path %> before creating a invoice!
  </div>

<% end %>

<div class="p-5 border-dark border mt-5">

  <%= render partial: 'invoice_form', locals: {invoice: @invoice}  %>

</div>

app/views/invoices/old2/show.html.erb
<br><br>


<div class="invoice p-5">

  <% if @invoice %>
    <%= render partial: 'show_invoice', locals: {invoice: @invoice} %>
  <% else %>
    <h4>Invoice does not exist!</h4>
  <% end %>


</div>

app/views/invoices/old2/unsent.html.erb
<div class="row">
  <div class="col">
    <%= render partial: 'list_invoices', locals: {invoices: @invoices} %>
  </div>

</div>